import React from 'react';
import './App.css';
import CustomerAddModel from './pages/Customer/CustomerAddModel';
import MainPage from './pages/MainPage/MainPage';
import { PrintComponent } from './pages/PrintCoponent/PrintComponent';

export default function App() {
  const tsble={
    "cusNames": 2,
    "name": "Ajay ",
    "gst": "89898",
    "supply": "98989",
    "sac": "9898",
    "address": "9898",
    "narration": "this is a manual narration",
    "invoiceNumber": " klkl",
    "invoiceDate": "04.05.2024",
    "cdc": 0,
    "oda": 0,
    "acc": 0,
    "ccc": 0,
    "otherc": 0,
    "cgst": 0,
    "igst": 0,
    "sgst": 0,
    "tableData": [
        {
            "date": "04.05.2024",
            "consignmentNoteNumber": "lkk",
            "network": "lk",
            "consignee": "lk",
            "destination": "k",
            "weight": 0,
            "pcs": 0,
            "fuelper": 0,
            "freight": 0,
            "fuelAmount": 0,
            "amount": 0
        },
        {
            "date": "04.05.2024",
            "consignmentNoteNumber": "lkl",
            "network": "lk",
            "consignee": "lk",
            "destination": "lk",
            "weight": 0,
            "pcs": 0,
            "fuelper": 0,
            "freight": 0,
            "fuelAmount": 0,
            "amount": 0
        },
        {
            "date": "04.05.2024",
            "consignmentNoteNumber": "kjkj",
            "network": "kj",
            "consignee": "kj",
            "destination": "kj",
            "weight": 0,
            "pcs": 0,
            "fuelper": 0,
            "freight": 0,
            "fuelAmount": 0,
            "amount": 0
        },
        {
            "date": "04.05.2024",
            "consignmentNoteNumber": "kjj",
            "network": "kj",
            "consignee": "kj",
            "destination": "kj",
            "weight": 0,
            "pcs": 9,
            "fuelper": 0,
            "freight": 0,
            "fuelAmount": 0,
            "amount": 0
        },
        {
            "date": "11.05.2024",
            "consignmentNoteNumber": "jkkj",
            "network": "kj",
            "consignee": "k",
            "destination": "kj",
            "weight": 0,
            "pcs": 0,
            "fuelper": 0,
            "freight": 0,
            "fuelAmount": 0,
            "amount": 0
        },
        {
            "date": "04.05.2024",
            "consignmentNoteNumber": "  jkjk",
            "network": "jk",
            "consignee": "jkj",
            "destination": "kj",
            "weight": 0,
            "pcs": 0,
            "fuelper": 0,
            "freight": 0,
            "fuelAmount": 0,
            "amount": 0
        },
        {
            "date": "04.05.2024",
            "consignmentNoteNumber": "klk",
            "network": "lk",
            "consignee": "lk",
            "destination": "lk",
            "weight": 0,
            "pcs": 0,
            "fuelper": 0,
            "freight": 0,
            "fuelAmount": 0,
            "amount": 0
        },
        {
            "date": "04.05.2024",
            "consignmentNoteNumber": "jkj",
            "network": "kj",
            "consignee": "kj",
            "destination": "kj",
            "weight": 0,
            "pcs": 0,
            "fuelper": 0,
            "freight": 0,
            "fuelAmount": 0,
            "amount": 0
        },
        {
            "date": "04.05.2024",
            "consignmentNoteNumber": "jkkj",
            "network": "kjkj",
            "consignee": "kj",
            "destination": "kj",
            "weight": 0,
            "pcs": 0,
            "fuelper": 0,
            "freight": 0,
            "fuelAmount": 0,
            "amount": 0
        },
        {
            "date": "11.05.2024",
            "consignmentNoteNumber": "lkkl",
            "network": "k",
            "consignee": "lk",
            "destination": "lk",
            "weight": 0,
            "pcs": 0,
            "fuelper": 0,
            "freight": 0,
            "fuelAmount": 0,
            "amount": 0
        },
        {
            "date": "11.05.2024",
            "consignmentNoteNumber": "kl",
            "network": "lk",
            "consignee": "lk",
            "destination": "lklk",
            "weight": 0,
            "pcs": 0,
            "fuelper": 0,
            "freight": 0,
            "fuelAmount": 0,
            "amount": 0
        },
        {
            "date": "18.05.2024",
            "consignmentNoteNumber": "jkkj",
            "network": "kj",
            "consignee": "kj",
            "destination": "kjkj",
            "weight": 0,
            "pcs": 0,
            "fuelper": 0,
            "freight": 0,
            "fuelAmount": 0,
            "amount": 0
        },
        {
            "date": "18.05.2024",
            "consignmentNoteNumber": "jkjkj",
            "network": "kj",
            "consignee": "kj",
            "destination": "kj",
            "weight": 0,
            "pcs": 0,
            "fuelper": 0,
            "freight": 0,
            "fuelAmount": 0,
            "amount": 0
        },
        {
            "date": "11.05.2024",
            "consignmentNoteNumber": "kllk",
            "network": "lk",
            "consignee": "lk",
            "destination": "lk",
            "weight": 0,
            "pcs": 0,
            "fuelper": 0,
            "freight": 0,
            "fuelAmount": 0,
            "amount": 0
        },
        {
            "date": "18.05.2024",
            "consignmentNoteNumber": "opopopo",
            "network": "klklk",
            "consignee": "lklklk",
            "destination": "lklk",
            "weight": 0,
            "pcs": 0,
            "fuelper": 0,
            "freight": 0,
            "fuelAmount": 0,
            "amount": 0
        },
        {
            "date": "18.05.2024",
            "consignmentNoteNumber": "kjjkj",
            "network": "kjkjkj",
            "consignee": "kjkkj",
            "destination": "kjkj",
            "weight": 0,
            "pcs": 0,
            "fuelper": 0,
            "freight": 0,
            "fuelAmount": 0,
            "amount": 0
        },
        {
            "date": "11.05.2024",
            "consignmentNoteNumber": "jkj",
            "network": "jkj",
            "consignee": "j",
            "destination": "j",
            "weight": 0,
            "pcs": 0,
            "fuelper": 0,
            "freight": 0,
            "fuelAmount": 0,
            "amount": 0
        },
        {
            "date": "18.05.2024",
            "consignmentNoteNumber": "kjjlk",
            "network": "jlkj",
            "consignee": "lkjlk",
            "destination": "jlkj",
            "weight": 0,
            "pcs": 0,
            "fuelper": 0,
            "freight": 0,
            "fuelAmount": 0,
            "amount": 0
        },
        {
            "date": "11.05.2024",
            "consignmentNoteNumber": "jh",
            "network": "jkh",
            "consignee": "jkhkj",
            "destination": "hkjhkjh",
            "weight": 0,
            "pcs": 0,
            "fuelper": 0,
            "freight": 0,
            "fuelAmount": 0,
            "amount": 0
        },
        {
            "date": "18.05.2024",
            "consignmentNoteNumber": "kjkjl",
            "network": "jlk",
            "consignee": "jlkjlk",
            "destination": "jkljl",
            "weight": 0,
            "pcs": 0,
            "fuelper": 0,
            "freight": 0,
            "fuelAmount": 0,
            "amount": 0
        },
        {
            "date": "18.05.2024",
            "consignmentNoteNumber": "jhkjh",
            "network": "jkhkjhkjh",
            "consignee": "jhkjhkjhk",
            "destination": "jkhkjhkjh",
            "weight": 0,
            "pcs": 0,
            "fuelper": 0,
            "freight": 0,
            "fuelAmount": 0,
            "amount": 0
        }
    ],
    "grandTotal": 0,
    "cgstCharges": 0,
    "sgstCharges": 0,
    "igstCharges": 0,
    "roundoff": 0,
    "finalTotal": 0,
    "cdcTotal": 0,
    "odaTotal": 0,
    "accTotal": 0,
    "otherCharges": 0,
    "cccCharges": 0,
    "total": 0
}
  return <MainPage  />
  // return <PrintComponent printData={tsble} />
  // return <div>Helloo</div>;

}


